config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'charts/volunteer'
  get 'charts/tags'
  get 'charts/adventures'

  root to: 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get 'login' => 'home#index', as: :login
  delete 'logout', to: 'sessions#destroy'

  patch '/select_club/:id', to: 'home#select_club', as: :select_club

  resource :account, only: [:show, :update]

  resources :tags, only: :index
  resources :emails, only: :create
  resources :users, only: [:create, :update, :show]
  resources :volunteers, except: [:edit, :destroy, :show]

  resources :reports do
    resources :report_items, only: [:create, :update, :destroy], shallow: true
  end

  resources :clubs, only: [:index, :edit, :update] do
    member do
      patch :enable
      patch :disable
    end
  end

  resources :adventures, except: [:destroy, :show] do
    member do
      post :track_time
      post :set_time_for_volunteers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login

  skip_after_action  :verify_authorized

  def index
  end

  def select_club
    service = SessionClubService.new(current_user)

    current_user
      .selected_club = service.selected_club session,
                                             Club.find_by(id: params[:id])

    redirect_back(fallback_location: root_path)
  end
end

app/views/home/_logged_in.html.erb
<div class="container">
  <div class="expanded row">
    <% if current_user.selected_club.present? %>
        <div class="small-12 large-4 large-push-8 columns">
          <div class="expanded row chart-container">
            <div class="small-12 medium-6 large-12 columns">
              <div class="chart">
                <h5 class="chart-heading">Top Volunteers</h5>
                <%= column_chart charts_volunteer_path(
                                     club_id:    current_user.selected_club.id,
                                     start_time: DateTime.current.beginning_of_year,
                                     end_time:   DateTime.current,
                                     top:        10) %>
              </div>
            </div>
            <div class="small-12 medium-6 large-12 columns">
              <div class="chart">
                <h5 class="chart-heading">Top Tags</h5>
                <%= donut_chart charts_tags_path(
                                    club_id:    current_user.selected_club.id,
                                    start_time: DateTime.current.beginning_of_year,
                                    end_time:   DateTime.current,
                                    top:        10) %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <div class="small-12 large-8 large-pull-4 columns">
      <div class="expanded row card-container" data-equalizer data-equalize-on="medium">
        <% current_user.clubs.enabled.includes(:adventures, :incentives).each do |club| %>
            <%= render 'clubs/card_club', club: club if club.adventures.present? %>
            <%= render 'home/reveal_incentives', club: club if club.adventures.present? %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_login.html.erb
<div class="expanded row fold fold-home">
    <div class="fold-background background-login"></div>
    <div class="fold-content">
        <%= image_tag "logos/yazda_full_horizontal_shadow.svg", class: 'homepage-logo' %>
        <a href="/auth/yazda" class="expanded button energized login-submit-btn">Login With Yazda!</a>
    </div>
</div>

app/views/home/_reveal_incentives.html.erb
<div id="incentives-panel-<%= club.id %>"
     class="full reveal profile-panel incentives-panel" data-overlay="false"
     data-reveal data-animation-in="fade-in" data-animation-out="fade-out">
  <a class="close-button" title="Close panel" data-close>&times;</a>

  <div class="panel-inner">
    <div class="media-object">
      <div class="media-object-section middle">
        <div class="user-avatar lg">
          <%= yazda_image_tag club.profile_image_url %>
        </div>
      </div>
      <div class="media-object-section middle">
        <h4 class="club-name">
          <a href="https://yazdaapp.com/clubs/<%= club.yazda_club_id %>"
             target="_blank" title="View on yazda"><%= club.name %></a>
        </h4>
        <h5 class="hours-worked">
          Hours this
          year:<span> <%= current_user.year_to_date_volunteers_for_club(club).sum(:hours) %></span>
        </h5>
        <h6 class="last-attended">
          Last
          attended:<span> <%= current_user.last_attended_for_club(club) %></span>
        </h6>
      </div>
    </div>

    <div class="incentive-container">

      <%= render 'incentives/incentive', club: club, user: current_user %>

      <hr/>

      <div class="media-object">
        <div class="media-object-section middle">
          <div class="user-avatar sm">
            <%= yazda_image_tag current_user.profile_image_url %>
          </div>
        </div>
        <div class="media-object-section middle">
          <h5 class="user-name">
            <a href="https://yazdaapp.com/users/<%= current_user.yazda_user_id %>"
               target="_blank" title="View on yazda"><%= current_user.name %></a>
          </h5>
        </div>
      </div>


      <% if club.incentives.each do |incentive| %>
          <div class="incentive-tooltip <%= 'complete' if incentive_completed incentive, club, current_user %>">
            <h6>
              <strong><%= incentive.hours %> Hours</strong>
              <% if incentive_completed incentive, club, current_user %>
                  <span><i class="ion-checkmark-round" title="Milestone complete!"></i></span>
              <% else %>
                  <span><strong><%= incentive.hours - current_user.hours_for_club(club) %></strong> to go</span>
              <% end %>
            </h6>
            <%= incentive.description_markdown.html_safe %>
          </div>
      <% end.empty? %>
        <div class="incentive-tooltip placeholder-tooltip">
          <h6>
            There are no incentives for this club.
          </h6>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_volunteer_submit.html.erb
<div class="expanded row fold fold-submit-hours">

  <div class="fold-background background-submit-hours"
       style="background-image: url(<%= @volunteer.club.banner_image_url %>);
           background-image: url(<%= @volunteer.club.banner_image_url %>),
               url(<%= asset_url('backgrounds/work1.jpg') %>);"></div>

  <div class="fold-content">

    <h2 class="fold-heading">Please report your time</h2>

    <!-- Adventure info -->
    <div class="submit-hours-adventure-info">

      <div class="media-object">
        <div class="media-object-section middle">
          <div class="thumbnail">
            <div class="user-avatar sm"><%= image_tag @volunteer.adventure.owner_profile_image_url %>
            </div>
          </div>
        </div>
        <div class="media-object-section middle">
          <div class="hosted">
            Hosted by
            <a href="https://yazdaapp.com/clubs/<%= @volunteer.club.id %>"
               target="_blank" title="View Club">
              <%= @volunteer.club.name %>
            </a>
          </div>
        </div>
      </div>

      <h5 class="adventure-name"><%= @volunteer.adventure.name %></h5>
      <a href="#" class="location" title="View Location">
        <span><%= @volunteer.adventure.try :address %></span>
      </a>
      <a href="#" class="adventurers" target="_blank" title="View Adventurers">
        <%= @volunteer.adventure.volunteers.count %> Adventurers
      </a>
      <div class="duration">
        <i class="ion-android-time"></i><span> Duration: </span><strong>
        <%= distance_of_time_in_words(@volunteer.adventure.start_time,
                                      @volunteer.adventure.end_time) %>
      </strong>
      </div>

      <!-- Submit hours input/button -->
      <%= simple_form_for @volunteer,
                          html: {
                              class: 'submit-form submit-hours-form'
                          } do |f| %>
          <div class="row">
            <div class="small-6 columns">
              <%= f.input :hours, as:  :float, label: false, required: false,
                          placeholder: 'Hours', id: 'submit-time' %>
            </div>
            <div class="small-6 columns">
              <%= f.button :submit, 'Save',
                           class: 'expanded button energized submit-hours-btn' %>
            </div>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if @volunteer %>
    <%= render 'home/volunteer_submit' %>
<% elsif current_user %>
    <%= render 'home/logged_in' %>
<% else %>
    <%= render 'home/login' %>
<% end %>