config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'charts/volunteer'
  get 'charts/tags'
  get 'charts/adventures'

  root to: 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get 'login' => 'home#index', as: :login
  delete 'logout', to: 'sessions#destroy'

  patch '/select_club/:id', to: 'home#select_club', as: :select_club

  resource :account, only: [:show, :update]

  resources :tags, only: :index
  resources :emails, only: :create
  resources :users, only: [:create, :update, :show]
  resources :volunteers, except: [:edit, :destroy, :show]

  resources :reports do
    resources :report_items, only: [:create, :update, :destroy], shallow: true
  end

  resources :clubs, only: [:index, :edit, :update] do
    member do
      patch :enable
      patch :disable
    end
  end

  resources :adventures, except: [:destroy, :show] do
    member do
      post :track_time
      post :set_time_for_volunteers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  include FriendlyId

  friendly_id :url_candidates, use: :slugged

  belongs_to :club
  has_many :report_items, -> { order(position: :asc) }, dependent: :destroy

  enum status: [:draft, :published, :archived]

  validates :name, presence: true, length: { maximum: 255, minimum: 3 }
  validates :url, presence: true, length: { maximum: 255, minimum: 3 }
  validates :primary_color,
            allow_blank: true,
            format:      { with:    /\A([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})\z/,
                           message: 'must be a valid hex color' }

  validates :secondary_color,
            allow_blank: true,
            format:      { with:    /\A([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})\z/,
                           message: 'must be a valid hex color' }
  validates :start_date, presence: true
  validates :club_id, presence: true

  def hours
    adventures_ar.joins(:volunteers).sum(:hours)
  end

  def volunteers
    adventures_ar.joins(:volunteers).group(:user_id).distinct.count.count
  end

  def adventures
    adventures_ar.count
  end

  def url_candidates
    [
      :url,
      [:url, Date.current.year]
    ]
  end

  private

  def adventures_ar
    Adventure.reportable.in_date(start_date.to_s, end_date.to_s)
      .filter(tags_list)
      .where(club_id: club_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout 'public', only: :show

  skip_before_action :require_login, only: :show
  skip_after_action :verify_authorized

  def index
    authorize Report

    @reports = current_user.selected_club.reports
  end

  def create
    @report = current_user.selected_club.reports.build(create_params)
    authorize @report

    if @report.save
      redirect_to edit_report_path @report
    else
      render :new
    end
  end

  def new
    @report = current_user.selected_club.reports.build
    authorize @report
  end

  def show
    @report = Report.friendly.find params[:id]
    authorize @report
  end

  def edit
    @report = Report.friendly.find params[:id]
    authorize @report
  end

  def update
    @report = Report.friendly.find params[:id]
    authorize @report

    @report.status = case params[:commit]
                     when 'Publish'
                       :published
                     when 'Draft'
                       :draft
                     else
                       @report.status
                     end

    if @report.update(update_params)
      redirect_to reports_path, notice: 'Report saved!'
    else
      render :edit
    end
  end

  def destroy
    @report = Report.friendly.find params[:id]
    authorize @report

    @report.archived!
    redirect_to reports_path
  end

  private

  def create_params
    params.require(:report).permit(:name, :url, :description, :start_date,
                                   :end_date)
  end

  def update_params
    params.require(:report).permit(:name, :description, :start_date,
                                   :end_date, :tags_list, :primary_color,
                                   :secondary_color)
  end

end

app/views/reports/_card_add_report.html.erb
<article class="card-wrapper" title="Create report">
  <div class="card card-add" data-equalizer-watch>
    <%= link_to new_report_path do %>
        <i class="ion-plus-round"></i>
    <% end %>
  </div>
</article>

app/views/reports/_report.html.erb
<%= render 'reports/reveal_share_report', report: report %>

<article class="card-wrapper">
  <div class="card card-report" data-equalizer-watch>
    <div class="card-preheader">
      <%= link_to report_path(report),
                  target: '_blank',
                  class:  'card-report-cta status-published',
                  title:  'This report is published. Click to View' do %>
          <i class="ion-checkmark-round"></i>
      <% end if report.published? %>
      <%= link_to edit_report_path(report),
                  class: 'card-report-cta blue',
                  title: 'Edit' do %>
          <i class="ion-compose"></i>
      <% end %>
      <% if report.published? %>
          <a class="card-report-cta" title="Share"
             data-open="reveal-share-report-<%= report.id %>">
            <i class="ion-android-share-alt"></i>
          </a>
      <% end %>
    </div>
    <div class="card-info">
      <h5 class="card-heading"><%= report.name %></h5>
      <p class="card-description"><%= report.description %></p>
    </div>
    <div class="card-footer">
      <div class="expanded row">
        <div class="small-4 columns">
          <h6 class="report-stats" title="Total volunteers">
            <i class="ion-ios-people"></i>
            <span class="sr-only">Volunteers</span>
            <span><%= report.volunteers %></span>
          </h6>
        </div>

        <div class="small-4 columns">
          <h6 class="report-stats" title="Total adventures">
            <i class="icon-adventures"></i>
            <span class="sr-only">Adventures</span>
            <span><%= report.adventures %></span>
          </h6>
        </div>

        <div class="small-4 columns">
          <h6 class="report-stats" title="Total hours">
            <i class="ion-android-time"></i>
            <span class="sr-only">Hours</span>
            <span><%= report.hours %></span>
          </h6>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/reports/_reveal_share_report.html.erb
<div class="reveal" id="reveal-share-report-<%= report.id %>" data-reveal
     data-animation-in="fade-in" data-animation-out="fade-out">
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>

  <% unless report.published? %>
      <div class="share-notification-banner">
        <p>You need to publish this report in order to share the link.</p>
      </div>
  <% end %>

  <ul class="tabs share-report-tabs" id="share-report-tabs-<%= report.id %>" data-tabs>
    <li class="tabs-title is-active" aria-selected="true">
      <a href="#share-social-media-<%= report.id %>">Share</a>
    </li>
    <li class="tabs-title">
      <a href="#share-embed-<%= report.id %>">Embed</a>
    </li>
    <!--TODO this-->
    <!--<li class="tabs-title">-->
    <!--<a href="#share-email-<%= report.id %>">Email</a>-->
    <!--</li>-->
  </ul>

  <div class="tabs-content" data-tabs-content="share-report-tabs-<%= report.id %>">

    <div class="tabs-panel is-active" id="share-social-media-<%= report.id %>">
      <div class="input-group">
        <input class="string required share-report-url"
               value="<%= url_for(controller: :reports, action: :show,
                                  id:         report.slug, only_path: false) %>"
               name="report[link]"
               id="report_link-<%= report.id %>" type="text">
        <div class="input-group-button">
          <button class="button secondary copy-button" data-clipboard-action="copy" data-clipboard-target="#report_link-<%= report.id %>">Copy</button>
        </div>
      </div>
      <p class="help-text">Copy this link onto your clipboard.</p>

      <div class="social-share-container md">
        <%= social_share_button_tag(report.name, url: url_for(controller: :reports, action: :show,
                                                              id:         report.slug,
                                                              only_path:  false)) %>
      </div>
      <p class="help-text">Share with social media.</p>
    </div>

    <div class="tabs-panel" id="share-embed-<%= report.id %>">
      <div class="input-group">
        <input class="string required share-report-embed" value="
&lt;iframe width=&quot;560&quot; height=&quot;346&quot; src=&quot;<%= url_for(controller: :reports, action: :show, id: report.slug, only_path: false) %>&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;"
               name="report[iframe]" id="report_embed-<%= report.id %>"
               type="text" title="Embed code">
        <div class="input-group-button">
          <button class="button secondary copy-button" data-clipboard-action="copy" data-clipboard-target="#report_embed-<%= report.id %>">Copy</button>
        </div>
      </div>
      <p class="help-text">Embed this report code on your website.</p>
    </div>

    <div class="tabs-panel" id="share-email-<%= report.id %>">
      <form>
        <div class="input-group">
          <input class="string email required" placeholder="To" name="user[email]" id="user_email" type="email">
        </div>

        <div class="input-group">
          <input class="string required" placeholder="Subject" name="email[subject]" id="email_subject" type="text">
        </div>

        <div class="input-group">
          <textarea class="text required" placeholder="Optional message..." name="email[message]" id="email_message"></textarea>
        </div>

        <input name="commit" value="Send" class="button sm expanded energized" data-disable-with="Send" type="submit">
      </form>
    </div>
  </div>
</div>

app/views/reports/_show-report-header.html.erb
<header class="top-bar show-report-header">

    <div class="cta-container">
      <button class="button settings-toggle" title="Share this report"
              data-open="reveal-share-report-<%= @report.id %>">
        <i class="ion-android-share-alt"></i></button>
      <!-- Print Report -->
      <button class="button settings-toggle print-report" title="Print this report">
        <i class="ion-android-print"></i></button>
        <script>
          $('.print-report').click(function() {
            window.print();
          });
        </script>
    </div>

    <div class="header-logo">
      <%= link_to :root do %>
          <%= image_tag 'logos/yazda_full_horizontal.svg', class: 'header-logo' %>
      <% end %>
    </div>

  <% unless @report.published? %>
      <div class="volunteer-error" data-closable>
        This report has not been published yet. Publish it to make it available
        for other people to view.
        <button class="close-button" data-close aria-label="Close error" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  <% end %>

</header>

app/views/reports/edit.html.erb
<%= render 'reports/reveal_share_report', report: @report %>

<%= simple_form_for @report do |f| %>
<div id="report-filter-panel" class="filter-search-panel report-filter-panel" data-toggler data-animate="fade-in fade-out" data-closable>
  <a class="close-button" title="Close panel" data-close>&times;</a>

  <%= link_to report_url(@report), @report,
                  target: '_blank',
                  class: 'report-info-url' %>

  <div class="expanded row">
    <div class="small-12 columns">
      <%= f.input :name,
                  placeholder: 'Report Name',
                  hint:        'Enter a report name.',
                  label:       false,
                  required:    false %>
    </div>
    <div class="small-12 columns">
      <%= f.input :description,
                  placeholder: 'Description',
                  hint:        'Enter a brief description.',
                  rows:        '4',
                  label:       false,
                  required:    false %>
    </div>
  </div>

  <div class="expanded row">
    <div class="small-12 large-4 columns">
      <h5 class="filter-heading single-line-text">Date</h5>
      <div class="expanded row">
        <div class="small-6 columns">
          <%= f.input :start_date, as: :date_picker,
                      label:           false,
                      required:        false,
                      hint:            'Start date.',
                      placeholder:     'Start Date',
                      hint:            'Enter start date.' %>
        </div>
        <div class="small-6 columns">
          <%= f.input :end_date, as: :date_picker,
                      label:         false,
                      hint:          'End date.',
                      placeholder:   'End Date',
                      hint:          'Enter end date.' %>
        </div>
      </div>
    </div>

    <div class="small-12 large-5 columns filter-tag-wrapper">
      <h5 class="filter-heading single-line-text">Filter by tag</h5>
      <%= f.input :tags_list,
                  label:      false,
                  as:         :string,
                  input_html: {
                      class:              'dynamic-selectize-control selectized',
                      'aria-describedby': 'tag-help-text',
                      placeholder:        "Type to add tag...",
                      data:               {
                          context: ''
                      }
                  } %>
      <p class="help-text" id="tag-help-text">Type to add tags and press
        enter. Backspace to delete.</p>
    </div>

    <div class="small-12 large-3 columns">
      <h5 class="filter-heading single-line-text">Colors</h5>
      <div class="expanded row">
        <div class="small-6 columns">
          <%= f.input :primary_color,
                      label:      false,
                      input_html: {
                          class: "volunteer-search jscolor {borderColor:'#000000', backgroundColor:'#303030'}"
                      } %>
        </div>
        <div class="small-6 columns">
          <%= f.input :secondary_color,
                      label:      false,
                      input_html: {
                          class: "volunteer-search jscolor {borderColor:'#000000', backgroundColor:'#303030'}"
                      } %>
        </div>
      </div>
      <p class="help-text" id="tag-help-text">Select colors for all
        charts.</p>
    </div>
  </div>
</div>

<!-- BEGIN FORM CTA BUTTONS -->
<div class="expanded row create-cta-container">
  <div class="expanded button-group">
    <%= f.submit 'Save',
                 class: 'button energized save-report-btn',
                 title: 'Save latest changes' %>
    <%= link_to 'Preview', @report,
                class:  'button secondary',
                title:  'Preview latest changes',
                target: '_blank' %>

    <%= f.submit 'Publish',
                 class: 'button primary',
                 title: 'Publish report (link will be visible)' if @report.draft? %>
    <%= f.submit 'Draft',
                 class: 'button warning',
                 title: 'Revert report back to draft (link will not be visible)' if @report.published? %>
    <%= link_to 'Archive', @report, method: :delete,
                class:                      'button alert report-delete-btn' %>
  </div>
</div>
<!-- END CTA BUTTONS -->
<% end %>


<div class="container create-report-container">
  <div class="expanded row">
    <div class="small-12 large-3 large-push-9 columns sidebar create-report-sidebar" data-sticky-container>
      <div class="expanded row report-add-item-container sticky" data-sticky data-margin-top="0" data-top-anchor="60">
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :donut_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/donut-chart.jpg', class: 'add-item-img' %>
            <span class="add-item-name">Donut</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :pie_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/pie-chart.jpg', class: 'add-item-img' %>
            <span class="add-item-name">Pie</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :bar_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/bar-chart.jpg', class: 'add-item-img' %>
            <span class="add-item-name">Bar</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :line_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/line-chart.png', class: 'add-item-img' %>
            <span class="add-item-name">Line</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :area_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/area-chart.png', class: 'add-item-img' %>
            <span class="add-item-name">Area</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :scatter_chart
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/scatter-chart.jpg', class:
                'add-item-img' %>
            <span class="add-item-name">Scatter</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :heading
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/heading.jpg', class: 'add-item-img' %>
            <span class="add-item-name">Header</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :text
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <%= image_tag 'reports/paragraph.jpg', class: 'add-item-img' %>
            <span class="add-item-name">Paragraph</span>
        <% end %>
        <%= button_to report_report_items_path(@report),
                      params: {
                          report_item: {
                              item_type: :hr
                          }
                      },
                      remote: true,
                      method: :post,
                      class:  'button add-item-btn',
                      title:  'Click to add' do %>
            <hr/>
            <span class="add-item-name">Divider</span>
        <% end %>
        <!--TODO images:-->
        <!--<button class="button add-item-btn" title="Click to add">-->
        <!--<%= image_tag 'reports/image.png', class: 'add-item-img' %>-->
        <!--<span class="add-item-name">Image</span>-->
        <!--</button>-->
      </div>
    </div>

    <div class="small-12 large-9 large-pull-3 columns">
      <% if @report.report_items.count == 0 %>
          <!-- BEGIN PLACEHOLDER FOR EMPTY CANVAS -->
          <div class="expanded row create-report-canvas">
            <h3 class="placeholder-heading">Add items to create your
              report</h3>
          </div>
          <!-- END PLACEHOLDER FOR EMPTY CANVAS -->
      <% else %>
          <!-- BEGIN FILLED CANVAS -->
          <div class="expanded row create-report-canvas filled">

            <!-- BEGIN DRAGGABLE CONTENT -->
            <ul class="menu vertical drag-container">
              <%= render @report.report_items %>
            </ul>
            <!-- END DRAGGABLE CONTENT -->
          </div>
          <!-- END FILLED CANVAS -->
      <% end %>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="container">
  <div class="expanded row">
    <div class="small-12 large-8 columns">
      <div class="expanded row card-container" data-equalizer data-equalize-on="medium">
        <%= render @reports %>
        <%= render 'reports/card_add_report' %>
      </div>
    </div>
    <div class="small-12 large-4 columns"></div>
  </div>
</div>

app/views/reports/new.html.erb
<%= simple_form_for @report, id: "report-info-form" do |f| %>
    <h4 class="reveal-heading">Create Report
      <span class="help-text">Enter basic report info here. You can update info at any time.</span>
    </h4>
    <div class="expanded row">
      <div class="small-12 columns">
        <%= f.input :name, hint: 'Enter a report name.' %>
      </div>
      <div class="small-6 medium-12 columns">
        <%= f.input :start_date, as: :date_picker, placeholder: 'Start Date',
                    hint:            'Enter start date.' %>
      </div>
      <div class="small-6 medium-12 columns">
        <%= f.input :end_date, as: :date_picker, placeholder: 'End Date (optional)',
                    hint:          'Enter end date.' %>
      </div>
      <div class="input-group">
        <span class="input-group-label" for="">https://volunteers.yazdaapp
          .com/reports/</span>
        <%= f.input_field :url, class: 'input-group-field' %>
        <%= f.full_error :url %>
      </div>
      <span class="help-text">Enter URL/Slug where you want users to view report.</span>
      <%= f.input :description, hint: 'Enter a brief description' %>
    </div>

    <div class="expanded row">
      <div class="small-12 columns">
        <%= f.submit 'Save', class: 'button expanded sm energized' %>
      </div>
    </div>
<% end %>

app/views/reports/show.html.erb
<%= render 'reports/reveal_share_report', report: @report %>
<%= render 'reports/show-report-header' %>

<div class="container show-report-container">

  <div class="expanded row banner-show show-report-banner">
    <div class="show-adventure-background"
         style="background-image: url(<%= @report.club.banner_image_url %>);"></div>
    <div class="media-object stack-for-small show-content">
      <div class="media-object-section middle">
        <div class="user-avatar profile">
          <%= yazda_image_tag @report.club.profile_image_url %>
        </div>
      </div>
      <div class="media-object-section middle">
        <h3 class="show-report-title"><%= @report.name %></h3>
        <h5 class="show-report-club-name">
          Published by
          <a target="_blank" title="View On Yazda" href="https://yazdaapp.com/clubs/<%= @report.club.yazda_club_id %>">
            <%= @report.club.name %>
          </a>
        </h5>
        <p>
          <button class="show-description-btn" data-toggle="show-report-description-panel">
            <i class="ion-chevron-down"></i>
            More...</button>
        </p>
      </div>
    </div>
  </div>

  <div class="expanded row">

    <div class="small-12 large-9 columns">

      <div id="show-report-description-panel" class="show-report-description-panel" data-toggler data-animate="fade-in fade-out">

        <div class="expanded row">

          <div class="small-12 large-9 columns">
            <p class="show-report-description">
              <%= @report.description %>
            </p>
            <div class="show-report-date">
              <i class="ion-android-time"></i>
              Start Date:
              <span><%= @report.start_date %></span>
            </div>
            <div class="show-report-date">
              <i class="ion-android-time"></i>
              End Date:
              <span><%= @report.end_date || Date.current %></span>
            </div>
          </div>
          <div class="small-12 large-3 columns">
          </div>
        </div>
      </div>

      <div class="expanded row show-report-stats-container">
        <div class="small-4 columns">
          <h6 class="report-stats" title="Total volunteers">
            <i class="ion-ios-people"></i>
            <span><%= @report.volunteers %></span>
            <span class="sr-only">Volunteers</span>
          </h6>
        </div>

        <div class="small-4 columns">
          <h6 class="report-stats" title="Total adventures">
            <i class="icon-adventures"></i>
            <span><%= @report.adventures %></span>
            <span class="sr-only">Adventures</span>
          </h6>
        </div>

        <div class="small-4 columns">
          <h6 class="report-stats" title="Total hours">
            <i class="ion-android-time"></i>
            <span><%= @report.hours %></span>
            <span class="sr-only">Hours</span>
          </h6>
        </div>
      </div>

      <div class="expanded row show-report-canvas">
        <% @report.report_items.each do |report_item| %>
            <% html_class = case report_item.item_type.to_sym
                            when :donut_chart, :pie_chart, :bar_chart, :line_chart,
                                :area_chart, :scatter_chart
                              'show-report-chart'
                            when :heading
                              'show-report-heading'
                            when :text
                              'show-report-paragraph'
                            end
            %>

            <div class="small-12 medium-<%= report_item.width %> columns
<%= html_class %>">
              <%= render 'report_items/report_header', report_item: report_item %>
            </div>
        <% end %>
      </div>

      <!--<div class="show-report-footer">-->
      <!--Copyright &copy;-->
      <!--<script type="text/javascript">-->
      <!-- // document.write(new Date().getFullYear()); -->
      <!--</script>-->
      <!--Club Name. All Rights Reserved.-->
      <!--</div>-->
    </div>

    <div class="small-12 large-3 columns hide-for-small-only show-report-sidebar ">
      <div class="expanded row">
        <h5 class="show-widget-heading">
          More Club Adventures
        </h5>
        <div class="show-widget-container">
          <div data-app_id="<%= ENV['YAZDA_API_KEY'] %>"
               data-club_id="<%= @report.club.yazda_club_id %>"
               data-theme="dark"
               data-background="1a1a1a"
               data-page_size="3"
               class="yazda-adventure-widget">
          </div>
          <script type="text/javascript" src="https://api.yazdaapp.com/assets/widgets.js"></script>
          <p class="show-widget-spacer">
            !!!This is a spacer to prevent sticky element from contracting.!!!
          </p>
        </div>
      </div>
    </div>
  </div>
</div>