config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'charts/volunteer'
  get 'charts/tags'
  get 'charts/adventures'

  root to: 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get 'login' => 'home#index', as: :login
  delete 'logout', to: 'sessions#destroy'

  patch '/select_club/:id', to: 'home#select_club', as: :select_club

  resource :account, only: [:show, :update]

  resources :tags, only: :index
  resources :emails, only: :create
  resources :users, only: [:create, :update, :show]
  resources :volunteers, except: [:edit, :destroy, :show]

  resources :reports do
    resources :report_items, only: [:create, :update, :destroy], shallow: true
  end

  resources :clubs, only: [:index, :edit, :update] do
    member do
      patch :enable
      patch :disable
    end
  end

  resources :adventures, except: [:destroy, :show] do
    member do
      post :track_time
      post :set_time_for_volunteers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if flash[:alert] %>
    <div id="volunteer-error" class="volunteer-error" data-closable><%= flash[:alert] %>
      <button class="close-button" data-close aria-label="Close error" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>
<% if flash[:notice] %>
    <div id="volunteer-notice" class="volunteer-notice" title="Close notice" data-closable><%= flash[:notice] %>
      <button class="close-button" data-close aria-label="Close notice" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

app/views/layouts/_reveal_email_volunteer.html.erb
<div class="reveal" id="reveal-email-volunteer" data-reveal data-animation-in="fade-in" data-animation-out="fade-out">
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
  <div id="email-form">
    <%= render 'volunteers/email_form' %>
  </div>
</div>

app/views/layouts/_reveal_filter_availability.html.erb
<div class="tiny reveal reveal-availability" id="reveal-filter-availability" data-reveal data-animation-in="fade-in" data-animation-out="fade-out">
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="reveal-heading">Availability Filter<span class="help-text">Select volunteer dates and times.</span>
    </h4>

    <div class="availability">
        <div class="row header">
            <div class="small-3 columns">
                <div class="heading calendar">
                    <i class="ion-calendar"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="heading">Mor
                    <i class="ion-ios-arrow-down"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="heading">Aft
                    <i class="ion-ios-arrow-down"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="heading">Eve
                    <i class="ion-ios-arrow-down"></i>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Mon
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_monday_morning"><input name="user[monday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[monday_morning]" id="user_monday_morning" type="checkbox">
                        <label class="boolean optional" for="user_monday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_monday_afternoon"><input name="user[monday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[monday_afternoon]" id="user_monday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_monday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_monday_evening"><input name="user[monday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[monday_evening]" id="user_monday_evening" type="checkbox">
                        <label class="boolean optional" for="user_monday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Tue
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_tuesday_morning"><input name="user[tuesday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[tuesday_morning]" id="user_tuesday_morning" type="checkbox">
                        <label class="boolean optional" for="user_tuesday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_tuesday_afternoon"><input name="user[tuesday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[tuesday_afternoon]" id="user_tuesday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_tuesday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_tuesday_evening"><input name="user[tuesday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[tuesday_evening]" id="user_tuesday_evening" type="checkbox">
                        <label class="boolean optional" for="user_tuesday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Wed
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_wednesday_morning"><input name="user[wednesday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[wednesday_morning]" id="user_wednesday_morning" type="checkbox">
                        <label class="boolean optional" for="user_wednesday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_wednesday_afternoon"><input name="user[wednesday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[wednesday_afternoon]" id="user_wednesday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_wednesday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_wednesday_evening"><input name="user[wednesday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[wednesday_evening]" id="user_wednesday_evening" type="checkbox">
                        <label class="boolean optional" for="user_wednesday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Thu
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_thursday_morning"><input name="user[thursday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[thursday_morning]" id="user_thursday_morning" type="checkbox">
                        <label class="boolean optional" for="user_thursday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_thursday_afternoon"><input name="user[thursday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[thursday_afternoon]" id="user_thursday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_thursday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_thursday_evening"><input name="user[thursday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[thursday_evening]" id="user_thursday_evening" type="checkbox">
                        <label class="boolean optional" for="user_thursday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Fri
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_friday_morning"><input name="user[friday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[friday_morning]" id="user_friday_morning" type="checkbox">
                        <label class="boolean optional" for="user_friday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_friday_afternoon"><input name="user[friday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[friday_afternoon]" id="user_friday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_friday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_friday_evening"><input name="user[friday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[friday_evening]" id="user_friday_evening" type="checkbox">
                        <label class="boolean optional" for="user_friday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Sat
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_saturday_morning"><input name="user[saturday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[saturday_morning]" id="user_saturday_morning" type="checkbox">
                        <label class="boolean optional" for="user_saturday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_saturday_afternoon"><input name="user[saturday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[saturday_afternoon]" id="user_saturday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_saturday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_saturday_evening"><input name="user[saturday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[saturday_evening]" id="user_saturday_evening" type="checkbox">
                        <label class="boolean optional" for="user_saturday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="small-3 columns">
                <div class="heading">Sun
                    <i class="ion-ios-arrow-right"></i>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_sunday_morning"><input name="user[sunday_morning]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[sunday_morning]" id="user_sunday_morning" type="checkbox">
                        <label class="boolean optional" for="user_sunday_morning">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_sunday_afternoon"><input name="user[sunday_afternoon]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[sunday_afternoon]" id="user_sunday_afternoon" type="checkbox">
                        <label class="boolean optional" for="user_sunday_afternoon">&nbsp;</label>
                    </div>
                </div>
            </div>
            <div class="small-3 columns">
                <div class="volunteer-checkbox-radio">
                    <div class="input boolean optional user_sunday_evening"><input name="user[sunday_evening]" value="0" type="hidden"><input class="boolean optional" value="1" name="user[sunday_evening]" id="user_sunday_evening" type="checkbox">
                        <label class="boolean optional" for="user_sunday_evening">&nbsp;</label>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/layouts/_side_nav.html.erb
<% if current_user && !@volunteer.present? && current_user.leader_clubs %>
    <!-- BEGIN OFF-CANVAS MENU -->
    <div class="off-canvas position-left reveal-for-large" id="offCanvasLeft" data-off-canvas>
      <!-- Close Button -->
      <button class="close-button hide-for-large" aria-label="Close menu" data-close title="Close Menu">
        <span aria-hidden="true">&times;</span>
      </button>
      <!-- Logo -->
      <div class="off-canvas-logo">
        <%= link_to :root do %>
            <%= image_tag 'logos/yazda_text_only.svg', class: '' %>
        <% end %>
      </div>
      <!-- Menu -->
      <ul class="vertical menu">
        <%= active_link_to root_url, wrap_tag: :li, active: :exclusive do %>
            <i class="ion-android-time"></i>
            <span>Dashboard</span>
        <% end %>
        <%= active_link_to adventures_path, wrap_tag: :li do %>
            <i class="icon-adventures"></i>
            <span>Adventures</span>
        <% end if policy(Adventure).index? %>
        <%= active_link_to volunteers_path, wrap_tag: :li do %>
            <i class="ion-ios-people"></i>
            <span>Volunteers</span>
        <% end if policy(Volunteer).index? %>
        <% if policy(Report).index? %>
            <%= active_link_to reports_path, wrap_tag: :li do %>
                <i class="ion-document"></i>
                <span>Reports</span>
            <% end %>
        <% end %>
        <%= active_link_to account_path, wrap_tag: :li do %>
            <i class="ion-toggle"></i>
            <span>Account</span>
        <% end %>
        <li>
          <%= link_to :logout, method: :delete do %>
              <i class="ion-log-out"></i>
              <span>Log Out</span>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- END OFF-CANVAS MENU -->
<% end %>

app/views/layouts/_top_nav.html.erb
<% if current_user && !@volunteer.present? && current_user.leader_clubs %>
    <!-- BEGIN HEADER -->
    <header>
      <div class="top-bar main-header">

        <!-- Off-Canvas Toggle -->
        <button class="button off-canvas-btn hide-for-large" data-toggle="offCanvasLeft" title="Open Menu">
          <i class="ion-navicon"></i>
          <span class="sr-only">Menu</span>
        </button>

        <div class="cta-container">
          <% if controller_name == 'adventures' && action_name == 'edit' %>
              <button class="button settings-toggle" title="Adventure settings" data-toggle="settings-panel">
                <i class="ion-android-options"></i></button>
              <% if @adventure.pending? %>
                  <button class="button settings-toggle" title="Add new volunteer" data-open="reveal-add-volunteer">
                    <i class="ion-person-add"></i></button>
              <% end %>
          <% end %>

          <% if controller_name == 'clubs' && action_name == 'edit' %>
              <%= active_link_to account_path, class: "button settings-toggle", title: "Back to account", style: "display: none;" do %>
                  <i class="ion-android-arrow-back"></i>
              <% end %>
          <% end %>

          <% if controller_name == 'accounts' && ['show', 'update'].include?(action_name) %>
              <button class="button settings-toggle" title="Set availability and skill tags" data-toggle="settings-panel">
                <i class="ion-android-options"></i></button>
          <% end %>

          <% if (controller_name == 'adventures' ||
              controller_name == 'volunteers') && action_name == 'index' %>
              <% if controller_name == 'adventures' %>
                  <%= link_to adventures_path({ format: :csv }.merge(params.permit(:filter, :q, :start_date, :end_date))),
                              class: "button settings-toggle download",
                              title: "Download CSV data" do %>
                      <i class="ion-android-download"></i>
                  <% end %>

                  <% if policy(Adventure).new? %>
                      <%= link_to new_adventure_path,
                                  class: "button add-adventure",
                                  title: "Add an adventure" do %>
                          <i class="icon-adventure-add"></i>
                      <% end %>
                  <% end %>
              <% end %>

              <% if controller_name == 'volunteers' %>
                  <%= link_to volunteers_path({ format: :csv }.merge(params.permit(:filter, :q, :start_date, :end_date))),
                              class: 'button settings-toggle download',
                              title: 'Download CSV data' do %>
                      <i class="ion-android-download"></i>

                  <% end %>
              <% end %>
              <button class="button search-toggle" title="Search for adventure or volunteer"
                      data-toggle="search-panel">
                <i class="ion-ios-search-strong"></i></button>
          <% end %>
          <% if controller_name == 'volunteers' && action_name =='index' %>
              <button class="button settings-toggle" title="Add new volunteer" data-open="reveal-add-volunteer">
                <i class="ion-person-add"></i></button>
              <button class="button settings-toggle" title="Email selected volunteers" data-open="reveal-email-volunteer">
                <i class="ion-email"></i></button>
          <% end %>
          <% if controller_name == 'reports' && action_name =='edit' %>
              <button class="button search-toggle" title="Share this report"
                      data-open="reveal-share-report-<%= @report.id %>">
                <i class="ion-android-share-alt"></i>
              </button>
              <button class="button search-toggle" title="Settings for report"
                      data-toggle="report-filter-panel">
                <i class="ion-android-options"></i>
              </button>
          <% end %>
        </div>

        <!-- Profile Image -->
        <%= link_to account_path, class: "user-avatar sm" do %>
            <%= yazda_image_tag current_user.profile_image_url, title: 'Account' %>
        <% end %>

        <!-- Club Select Dropdown -->
        <% if current_user.enabled_clubs.length > 1 %>
            <button class="button hollow balanced small select-club-btn float-right" data-toggle="club-list-select" title="Select A Club">
              <%= current_user.selected_club&.name || 'Select a Club' %>
              <i class="ion-chevron-down"></i>
            </button>
            <div class="dropdown-pane select-club-pane bottom" id="club-list-select" data-dropdown data-close-on-click="true">
              <ul class="menu vertical">
                <% current_user.enabled_clubs.each do |club| %>
                    <li>
                      <%= link_to select_club_path(club.id), method: :patch do %>
                          <i class="icon-clubs"></i>
                          <span><%= club['name'] %></span>
                      <% end %>
                    </li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </header>
    <!-- END HEADER -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "Volunteer Tracking" %></title>

  <%= favicon_link_tag 'apple-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57' %>
  <%= favicon_link_tag 'apple-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x60' %>
  <%= favicon_link_tag 'apple-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72' %>
  <%= favicon_link_tag 'apple-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76' %>
  <%= favicon_link_tag 'apple-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114' %>
  <%= favicon_link_tag 'apple-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120' %>
  <%= favicon_link_tag 'apple-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144' %>
  <%= favicon_link_tag 'apple-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152' %>
  <%= favicon_link_tag 'apple-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180' %>
  <%= favicon_link_tag 'android-icon-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192' %>
  <%= favicon_link_tag 'favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
  <%= favicon_link_tag 'favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96' %>
  <%= favicon_link_tag 'favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>
  <%= favicon_link_tag 'favicon.ico', rel: 'icon', type: 'image/x-icon' %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jscolor/2.0.4/jscolor.min.js"></script>
  <script src="https://cdn.jsdelivr.net/jquery.autogrow/1.2.2/jquery.autogrow.js"></script>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <% if Rails.env.production? %>
      <script>
        (function(i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r;
          i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
              }, i[r].l = 1 * new Date();
          a = s.createElement(o),
              m = s.getElementsByTagName(o)[0];
          a.async = 1;
          a.src = g;
          m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<%= Rails.application.secrets.ga_id %>', 'auto');
        ga('send', 'pageview');
        <% if current_user.present? %>
        ga('set', 'userId', <%= current_user.yazda_user_id %>);
        <% end %>
      </script>
  <% end %>
</head>

<body>

<%= render 'layouts/side_nav' %>

<!-- BEGIN CONTENT -->
<div class="off-canvas-content" data-off-canvas-content>
  <%= render 'layouts/errors' %>
  <%= render 'layouts/top_nav' %>
  <%= yield %>
  <%= csrf_meta_tags %>
</div>
<!-- END CONTENT -->

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "Volunteer Tracking" %></title>

  <%= favicon_link_tag 'apple-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57' %>
  <%= favicon_link_tag 'apple-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x60' %>
  <%= favicon_link_tag 'apple-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72' %>
  <%= favicon_link_tag 'apple-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76' %>
  <%= favicon_link_tag 'apple-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114' %>
  <%= favicon_link_tag 'apple-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120' %>
  <%= favicon_link_tag 'apple-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144' %>
  <%= favicon_link_tag 'apple-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152' %>
  <%= favicon_link_tag 'apple-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180' %>
  <%= favicon_link_tag 'android-icon-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192' %>
  <%= favicon_link_tag 'favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32' %>
  <%= favicon_link_tag 'favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96' %>
  <%= favicon_link_tag 'favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16' %>
  <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon', type: 'image/x-icon' %>
  <%= favicon_link_tag 'favicon.ico', rel: 'icon', type: 'image/x-icon' %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jscolor/2.0.4/jscolor.min.js"></script>
  <%= stylesheet_link_tag "application", media: :all %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <% if Rails.env.production? %>
      <script>
        (function(i, s, o, g, r, a, m) {
          i['GoogleAnalyticsObject'] = r;
          i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
              }, i[r].l = 1 * new Date();
          a = s.createElement(o),
              m = s.getElementsByTagName(o)[0];
          a.async = 1;
          a.src = g;
          m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', '<%= Rails.application.secrets.ga_id %>', 'auto');
        ga('send', 'pageview');
        <% if current_user.present? %>
        ga('set', 'userId', <%= current_user.yazda_user_id %>);
        <% end %>
      </script>
  <% end %>
</head>

<body>

<!-- BEGIN CONTENT -->
<div class="off-canvas-content" data-off-canvas-content>
  <%= render 'layouts/errors' %>
  <%= yield %>
  <%= csrf_meta_tags %>
</div>
<!-- END CONTENT -->
</body>
</html>