config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'charts/volunteer'
  get 'charts/tags'
  get 'charts/adventures'

  root to: 'home#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  get 'login' => 'home#index', as: :login
  delete 'logout', to: 'sessions#destroy'

  patch '/select_club/:id', to: 'home#select_club', as: :select_club

  resource :account, only: [:show, :update]

  resources :tags, only: :index
  resources :emails, only: :create
  resources :users, only: [:create, :update, :show]
  resources :volunteers, except: [:edit, :destroy, :show]

  resources :reports do
    resources :report_items, only: [:create, :update, :destroy], shallow: true
  end

  resources :clubs, only: [:index, :edit, :update] do
    member do
      patch :enable
      patch :disable
    end
  end

  resources :adventures, except: [:destroy, :show] do
    member do
      post :track_time
      post :set_time_for_volunteers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @clubs = policy_scope Club
  end

  def update
    current_user.update(account_params)
    @clubs = policy_scope Club

    render :show
  end

  private

  def account_params
    params.require(:user).permit(:monday_morning, :monday_afternoon,
                                 :monday_evening, :tuesday_morning,
                                 :tuesday_afternoon, :tuesday_evening,
                                 :wednesday_morning, :wednesday_afternoon,
                                 :wednesday_evening, :thursday_morning,
                                 :thursday_afternoon, :thursday_evening,
                                 :friday_morning, :friday_afternoon,
                                 :friday_evening, :saturday_morning,
                                 :saturday_afternoon, :saturday_evening,
                                 :sunday_morning, :sunday_afternoon,
                                 :sunday_evening, :skill_list)
  end
end

app/views/accounts/_edit_settings_account.html.erb
<div id="settings-panel" class="settings-panel" data-toggler data-animate="fade-in fade-out" data-closable>
  <div class="panel-inner">
    <button class="close-button" title="Close panel" data-close>&times;</button>

    <h4 class="panel-heading skillset" aria-describedby="skill-count">How
      can you help?</h4>

    <%= simple_form_for current_user, url: account_path,
                        class:             "filter-search-form" do |f| %>
        <%= f.input :skill_list,
                    label:      false,
                    hint:       'Type to add skill tags and press enter. Backspace
                    to delete.',
                    input_html: {
                        placeholder: "Type to add tag...",
                        value: f.object.skill_list.to_s
                    } %>

        <hr></hr>

        <h4 class="panel-heading">Availability
          <p class="help-text" id="tag-help-text">
            Set your time of day for availability.
          </p>
        </h4>

        <div class="availability">
          <div class="row header">
            <div class="small-3 columns">
              <div class="heading calendar">
                <i class="ion-calendar"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="heading">Mor
                <i class="ion-ios-arrow-down"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="heading">Aft
                <i class="ion-ios-arrow-down"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="heading">Eve
                <i class="ion-ios-arrow-down"></i>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Mon
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :monday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :monday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :monday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Tue
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :tuesday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:           :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :tuesday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:             :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :tuesday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:           :inline %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Wed
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :wednesday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:             :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :wednesday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:               :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :wednesday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:             :inline %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Thu
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :thursday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :thursday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:              :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :thursday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Fri
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :friday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :friday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :friday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Sat
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :saturday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :saturday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:              :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :saturday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="small-3 columns">
              <div class="heading">Sun
                <i class="ion-ios-arrow-right"></i>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :sunday_morning, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :sunday_afternoon, label: '&nbsp;'.html_safe,
                            boolean_style:            :inline %>
              </div>
            </div>
            <div class="small-3 columns">
              <div class="volunteer-checkbox-radio">
                <%= f.input :sunday_evening, label: '&nbsp;'.html_safe,
                            boolean_style:          :inline %>
              </div>
            </div>
          </div>
        </div>

        <%= f.submit 'Save', class: "button energized panel-save-btn" %>
    <% end %>

  </div>
</div>

app/views/accounts/show.html.erb
<%= render 'accounts/edit_settings_account' %>

<div class="container">

  <div class="expanded row banner-show">
    <div class="show-adventure-background"></div>
    <div class="media-object stack-for-small show-content">
      <div class="media-object-section middle">
        <div class="user-avatar profile">
          <%= yazda_image_tag current_user.profile_image_url %>
        </div>
      </div>
      <div class="media-object-section middle">
        <h3 class="show-user-name"><%= current_user.name %></h3>
        <h4 class="show-skills">
          <div class="volunteer-skills">
            <% current_user.skills.each do |s| %>
                <div class='tag-item'><%= s %></div>
            <% end %>
          </div>
        </h4>
      </div>
    </div>
  </div>

  <div class="expanded row">

    <div class="small-12 large-4 large-push-8 columns">
      <%= render 'incentives/incentives' %>
    </div>

    <div class="small-12 large-8 large-pull-4 columns">
      <div class="expanded row card-container" data-equalizer data-equalize-on="medium">
        <% @clubs.each do |club| %>
            <article class="card-wrapper">
              <div class="card" data-equalizer-watch>

                <%= link_to edit_club_path(club), class: "button club-edit-btn", title: "Edit club" do %>
                    <i class="ion-gear-a"></i>
                <% end %>

                <div class="card-background" style="background-image: url(<%= club.banner_image_url %>)"></div>

                <div class="card-header">
                  <div class="user-avatar md"><%= yazda_image_tag club.profile_image_url %></div>
                </div>

                <div class="card-info">
                  <h5 class="club-name">
                    <%= link_to edit_club_path(club) do %>
                        <%= club.name %>
                    <% end %>
                  </h5>
                </div>

                <% if club.enabled? %>
                    <!--TODO: Mark, we will have other statuses in the future-->
                    <!--payment declined-->
                    <div class="tracking enabled" title="Time Tracking: Enabled"><%= club.club_status.capitalize %></div>
                <% end %>
              </div>
            </article>
        <% end %>
      </div>
    </div>
  </div>
</div>